# Generated by Django 4.2.1 on 2024-02-19 06:39

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Course',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=200)),
            ],
        ),
        migrations.CreateModel(
            name='Mentor',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('user', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.CreateModel(
            name='Students',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=200)),
                ('package', models.CharField(choices=[('tranning+internship', 'tranning+internship'), ('tranning', 'tranning')], max_length=200)),
                ('payable_feel', models.CharField(max_length=200)),
                ('collage', models.CharField(max_length=200)),
                ('time_slog', models.CharField(max_length=200)),
                ('joined_date', models.DateTimeField(auto_now_add=True)),
                ('referred_by', models.CharField(max_length=200)),
                ('assigned_mentor', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='core.mentor')),
                ('course', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='core.course')),
            ],
        ),
    ]
