# Generated by Django 4.2.1 on 2024-02-19 06:45

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0002_course_mentor_students'),
    ]

    operations = [
        migrations.RenameField(
            model_name='students',
            old_name='time_slog',
            new_name='time_slot',
        ),
    ]
